const money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(Number(n||0));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
const seed={
 customers:[{id:'c1',name:'Juan',phone:'+27 82 000 0001',area:'Cape Town'},{id:'c2',name:'Ingrid',phone:'+27 82 000 0002',area:'Durbanville'},{id:'c3',name:'Conrad Kluyts',phone:'+27 82 000 0003',area:'Cape Town'}],
 products:[{id:'p1',name:'Boost Gel',sku:'GEL-BOOST',category:'Gel',price:21.9,stock:42,reorder:60},{id:'p2',name:'Peanut Butter Gel',sku:'GEL-PB',category:'Gel',price:21.9,stock:85,reorder:50},{id:'p3',name:'Vanilla Gel',sku:'GEL-VAN',category:'Gel',price:21.9,stock:31,reorder:50},{id:'p4',name:'Bottle Mix Tropical',sku:'BM-TROP',category:'Bottle Mix',price:21.8,stock:64,reorder:40},{id:'p5',name:'Bottle Mix Mixed Berry',sku:'BM-MB',category:'Bottle Mix',price:21.8,stock:27,reorder:40},{id:'p6',name:'Hydrate Lime 10-pack',sku:'HYD-LIME',category:'Hydrate',price:104.9,stock:18,reorder:15},{id:'p7',name:'Recover Chocolate',sku:'REC-CHO',category:'Recover',price:29.9,stock:22,reorder:25},{id:'p8',name:'Pea Protein 1kg',sku:'PEA-1KG',category:'Protein',price:240,stock:8,reorder:5}],
 raw:[{id:'r1',name:'Maltodextrin',unit:'kg',qty:28,min:15},{id:'r2',name:'Fructose',unit:'kg',qty:16,min:10},{id:'r3',name:'Sodium Citrate',unit:'kg',qty:4.2,min:3},{id:'r4',name:'Salt',unit:'kg',qty:6.5,min:2},{id:'r5',name:'WPC 80% Instant',unit:'kg',qty:12,min:8},{id:'r6',name:'Gel pouches',unit:'units',qty:780,min:500}],
 recipes:[{id:'rc1',name:'Bottle Mix 60g Base',output:1,items:[['Maltodextrin','40 g'],['Fructose','20 g'],['Sodium citrate','1 g'],['Salt','1 g']]},{id:'rc2',name:'Recover Base',output:1,items:[['WPC 80% Instant','20 g protein target'],['Carbohydrate blend','34 g carbs target']]}],
 orders:[{id:'o1',number:'JF-1842',customerId:'c1',date:'2026-09-30',status:'awaiting payment',source:'WhatsApp',items:[['p1',10],['p2',20],['p4',2]]},{id:'o2',number:'JF-1841',customerId:'c2',date:'2026-09-29',status:'paid',source:'Shopify',items:[['p4',3],['p3',5],['p7',4]]},{id:'o3',number:'JF-1840',customerId:'c3',date:'2026-09-29',status:'ready',source:'Shopify',items:[['p1',4],['p6',1]]}],
 batches:[{id:'b1',number:'B-0930-01',productId:'p1',qty:100,date:'2026-09-30',status:'planned'}],suppliers:[{id:'s1',name:'Primary ingredients supplier',contact:'Capture details'},{id:'s2',name:'Packaging supplier',contact:'Capture details'}]
};
let state=JSON.parse(localStorage.getItem('jfo-state')||'null')||seed,orderFilter='all',stockTab='finished';
const save=()=>localStorage.setItem('jfo-state',JSON.stringify(state));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const customer=id=>state.customers.find(x=>x.id===id)||{name:'Unknown'};
const product=id=>state.products.find(x=>x.id===id)||{name:'Unknown',price:0,stock:0};
const orderTotal=o=>o.items.reduce((t,[id,q])=>t+product(id).price*q,0);
function nav(view){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));render();scrollTo({top:0,behavior:'smooth'});}
function badge(s){let c=s==='paid'||s==='ready'?'good':s==='awaiting payment'?'warn':'';return `<span class="pill ${c}">${s}</span>`}
function render(){renderHome();renderOrders();renderProduction();renderStock();}
function renderHome(){const open=state.orders.filter(o=>!['ready','delivered','cancelled'].includes(o.status));const outstanding=state.orders.filter(o=>o.status==='awaiting payment').reduce((t,o)=>t+orderTotal(o),0);const low=state.products.filter(p=>p.stock<=p.reorder).length+state.raw.filter(r=>r.qty<=r.min).length;$('#kpis').innerHTML=[['Open orders',open.length],['Outstanding',money(outstanding)],['Low stock',low],['Customers',state.customers.length]].map(([l,v])=>`<div class="kpi"><div class="label">${l}</div><div class="value">${v}</div></div>`).join('');let alerts=[];state.products.filter(p=>p.stock<=p.reorder).slice(0,4).forEach(p=>alerts.push(`<div class="alert ${p.stock<p.reorder*.6?'bad':''}"><strong>${p.name}</strong> — ${p.stock} in stock, minimum ${p.reorder}.</div>`));$('#alerts').innerHTML=alerts.length?alerts.join(''):'<div class="muted">No stock alerts.</div>';$('#homeOrders').innerHTML=state.orders.slice(0,4).map(orderRow).join('');}
function orderRow(o){return `<div class="row"><div class="row-main"><strong>${o.number} · ${customer(o.customerId).name}</strong><small>${o.source} · ${o.items.reduce((t,x)=>t+x[1],0)} units · ${o.date}</small></div><div style="text-align:right"><div class="money">${money(orderTotal(o))}</div>${badge(o.status)}</div></div>`}
function renderOrders(){let arr=state.orders.filter(o=>orderFilter==='all'||o.status===orderFilter);$('#ordersList').innerHTML=arr.length?`<div class="panel">${arr.map(o=>`<div class="row"><div class="row-main"><strong>${o.number} · ${customer(o.customerId).name}</strong><small>${o.items.map(([id,q])=>`${q}× ${product(id).name}`).join(' · ')}</small></div><div style="text-align:right"><div class="money">${money(orderTotal(o))}</div>${badge(o.status)}</div></div>`).join('')}</div>`:'<div class="panel muted">No orders in this filter.</div>';}
function productionNeedData(){const req={};state.orders.filter(o=>!['ready','delivered','cancelled'].includes(o.status)).forEach(o=>o.items.forEach(([id,q])=>req[id]=(req[id]||0)+q));return Object.entries(req).map(([id,q])=>{const p=product(id);return {...p,ordered:q,need:Math.max(0,q-p.stock)}}).filter(x=>x.ordered>0).sort((a,b)=>b.need-a.need)}
function renderProduction(){const n=productionNeedData();$('#productionNeeds').innerHTML=n.length?n.map(x=>`<div class="row"><div class="row-main"><strong>${x.name}</strong><small>Orders ${x.ordered} · Stock ${x.stock}</small></div><div class="qty">${x.need?`Make ${x.need}`:'Covered'}</div></div>`).join(''):'<div class="muted">No open production demand.</div>';$('#batchList').innerHTML=state.batches.length?state.batches.map(b=>`<div class="row"><div class="row-main"><strong>${b.number} · ${product(b.productId).name}</strong><small>${b.date}</small></div><div><span class="qty">${b.qty}</span> ${badge(b.status)}</div></div>`).join(''):'<div class="muted">No batches yet.</div>';}
function renderStock(){if(stockTab==='finished'){$('#stockContent').innerHTML=`<div class="panel">${state.products.map(p=>`<div class="row"><div class="row-main"><strong>${p.name}</strong><small>${p.sku} · ${p.category}</small><div class="stockbar"><i style="width:${Math.min(100,p.stock/(p.reorder*2)*100)}%"></i></div></div><div style="text-align:right"><div class="qty">${p.stock}</div>${p.stock<=p.reorder?'<span class="pill warn">low</span>':''}</div></div>`).join('')}</div>`}else if(stockTab==='raw'){$('#stockContent').innerHTML=`<div class="panel">${state.raw.map(r=>`<div class="row"><div class="row-main"><strong>${r.name}</strong><small>Minimum ${r.min} ${r.unit}</small></div><div style="text-align:right"><div class="qty">${r.qty} ${r.unit}</div>${r.qty<=r.min?'<span class="pill warn">low</span>':''}</div></div>`).join('')}</div>`}else{$('#stockContent').innerHTML=state.recipes.map(r=>`<div class="panel"><div class="panel-head"><h3>${r.name}</h3><span class="pill">per ${r.output}</span></div>${r.items.map(i=>`<div class="row"><div>${i[0]}</div><strong>${i[1]}</strong></div>`).join('')}</div>`).join('')}}
function openModal(title,body,onSave){const d=$('#modal');$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalActions').innerHTML='<button value="cancel" class="secondary">Cancel</button><button type="button" id="modalSave" class="primary">Save</button>';$('#modalSave').onclick=()=>onSave(d);d.showModal();}
function newOrder(){openModal('New order',`<div class="field"><label>Customer</label><select id="fCustomer">${state.customers.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div class="grid2"><div class="field"><label>Source</label><select id="fSource"><option>WhatsApp</option><option>Shopify</option><option>Phone</option><option>Manual</option></select></div><div class="field"><label>Status</label><select id="fStatus"><option>new</option><option>awaiting payment</option><option>paid</option></select></div></div><div class="field"><label>Product</label><select id="fProduct">${state.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input id="fQty" type="number" inputmode="numeric" value="1" min="1"></div>`,()=>{const n=1843+state.orders.length;state.orders.unshift({id:uid('o'),number:`JF-${n}`,customerId:$('#fCustomer').value,date:new Date().toISOString().slice(0,10),status:$('#fStatus').value,source:$('#fSource').value,items:[[$('#fProduct').value,Number($('#fQty').value||1)]]});save();$('#modal').close();render();toast('Order created');});}
function newBatch(){openModal('Plan production batch',`<div class="field"><label>Product</label><select id="bProduct">${state.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></div><div class="field"><label>Quantity to manufacture</label><input id="bQty" type="number" value="100" min="1"></div>`,()=>{state.batches.unshift({id:uid('b'),number:`B-${new Date().toISOString().slice(5,10).replace('-','')}-${String(state.batches.length+1).padStart(2,'0')}`,productId:$('#bProduct').value,qty:Number($('#bQty').value),date:new Date().toISOString().slice(0,10),status:'planned'});save();$('#modal').close();render();toast('Batch planned');});}
function stockAdjust(){openModal('Adjust finished stock',`<div class="field"><label>Product</label><select id="sProduct">${state.products.map(p=>`<option value="${p.id}">${p.name} (${p.stock})</option>`).join('')}</select></div><div class="field"><label>New quantity</label><input id="sQty" type="number" min="0"></div><div class="field"><label>Reason</label><select id="sReason"><option>Stocktake</option><option>Production completed</option><option>Damaged</option><option>Correction</option></select></div>`,()=>{const p=product($('#sProduct').value);p.stock=Number($('#sQty').value);save();$('#modal').close();render();toast('Stock updated');});}
function morePanel(type){const el=$('#morePanel');el.classList.remove('hidden');if(type==='customers')el.innerHTML=`<div class="panel-head"><h3>Customers</h3><span>${state.customers.length}</span></div>${state.customers.map(c=>{const os=state.orders.filter(o=>o.customerId===c.id);return `<div class="row"><div class="row-main"><strong>${c.name}</strong><small>${c.phone} · ${c.area}</small></div><div>${os.length} orders</div></div>`}).join('')}`;if(type==='finance'){const a=state.orders.filter(o=>o.status==='awaiting payment').reduce((t,o)=>t+orderTotal(o),0);const paid=state.orders.filter(o=>['paid','ready','delivered'].includes(o.status)).reduce((t,o)=>t+orderTotal(o),0);el.innerHTML=`<div class="panel-head"><h3>Finance snapshot</h3></div><div class="row"><strong>Awaiting payment</strong><span class="money">${money(a)}</span></div><div class="row"><strong>Paid / ready</strong><span class="money">${money(paid)}</span></div>`}if(type==='suppliers')el.innerHTML=`<div class="panel-head"><h3>Suppliers</h3></div>${state.suppliers.map(s=>`<div class="row"><div><strong>${s.name}</strong><small>${s.contact}</small></div></div>`).join('')}`;if(type==='reports')el.innerHTML=`<div class="panel-head"><h3>Reports</h3></div><div class="row"><span>Total demo sales</span><span class="money">${money(state.orders.reduce((t,o)=>t+orderTotal(o),0))}</span></div>`;if(type==='settings')el.innerHTML='<div class="panel-head"><h3>Integrations</h3></div><div class="row"><div><strong>Supabase</strong><small>Backend tables ready</small></div><span class="pill good">Ready</span></div><div class="row"><div><strong>Shopify</strong><small>Webhook connector next</small></div><span class="pill warn">Setup</span></div><div class="row"><div><strong>WhatsApp Business</strong><small>Messaging connector next</small></div><span class="pill warn">Setup</span></div>';}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$$('[data-action="new-order"]').forEach(b=>b.onclick=newOrder);$('[data-action="new-batch"]').onclick=newBatch;$('[data-action="stock-adjust"]').onclick=stockAdjust;$$('#orderFilters button').forEach(b=>b.onclick=()=>{orderFilter=b.dataset.filter;$$('#orderFilters button').forEach(x=>x.classList.toggle('active',x===b));renderOrders()});$$('#stockTabs button').forEach(b=>b.onclick=()=>{stockTab=b.dataset.stocktab;$$('#stockTabs button').forEach(x=>x.classList.toggle('active',x===b));renderStock()});$$('[data-open-panel]').forEach(b=>b.onclick=()=>morePanel(b.dataset.openPanel));
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').hidden=true}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();
